name = "greecebydan-travel-api"
main = "worker.mjs"
compatibility_date = "2026-10-10"
workers_dev = true

[[ratelimits]]
name = "SEARCH_LIMIT"
namespace_id = "1047"
[ratelimits.simple]
limit = 20
period = 60
